const items = [
    {
      id: 1,
      title: "Калифорния хит",
      counter: 1,
      price: 300,
      weight: 180,
      itemsInBox: 6,
      img: "california-hit.jpg",
    },
    {
      id: 2,
      title: "Калифорния темпура",
      counter: 1,
      price: 250,
      weight: 205,
      itemsInBox: 6,
      img: "california-tempura.jpg",
    },
    {
      id: 3,
      title: 'Запечённый ролл "Калифорния"',
      counter: 1,
      price: 230,
      weight: 182,
      itemsInBox: 6,
      img: "zapech-california.jpg",
    },
    {
      id: 4,
      title: "Филадельфия",
      counter: 1,
      price: 320,
      weight: 230,
      itemsInBox: 6,
      img: "philadelphia.jpg",
    },
  ];